---
hosts:
  -
    settings:
      hostname: demo
      domain: startcloud.com
      server_id: '4020'
      vcpus: 2
      memory: 4G
      consoleport: 4020
      consolehost: 0.0.0.0
      box: 'STARTcloud/debian12-server'
      box_version: 0.0.3
      os_type: 'Debian_64'
      provider-type: virtualbox
      firmware_type: UEFI
      setup_wait: 300
      vagrant_user_private_key_path: ./core/ssh_keys/id_rsa
      vagrant_user: startcloud
      vagrant_user_pass: 'STARTcloud22@!'
      vagrant_insert_key: true
      ssh_forward_agent: true

    networks:
      - type: external
        address: 192.168.2.227
        netmask: 255.255.255.0
        gateway:
        dhcp4: true
        dhcp6: false
        bridge:
        mac: auto
        dns:
          - nameserver: 9.9.9.9
          - nameserver: 149.112.112.112

    #disks:
    #  boot:
    #    size: 24G
    #  additional_disks:
    #    - volume_name: disk1
    #      size: 20G
    #      port: 5

    provisioning:
      shell:
        enabled: false
        scripts:
          - './scripts/aliases.sh'

      ansible:
        enabled: true
        scripts:
          - local:
              - script: ansible/generate-playbook.yml
                ansible_python_interpreter: /usr/bin/python3
                compatibility_mode: 2.0
                install_mode: pip
                ssh_pipelining: true
                verbose: false
              - script: ansible/playbook.yml
                ansible_python_interpreter: /usr/bin/python3
                compatibility_mode: 2.0
                install_mode: pip
                ssh_pipelining: true
                verbose: false

    folders:
      - map: .
        to: /vagrant
        type: virtualbox
        disabled: true
        automount: true
        description: "Disable VBoxSF"
      - map: ./provisioners/ansible/
        to: /vagrant/ansible/
        type: rsync
        args:
          - '--verbose'
          - '--archive'
          - '--delete'
          - '-z'
          - '--copy-links'

    vars:
      debug_all: true

    roles:
      - name: startcloud_setup
      - name: startcloud_networking
      - name: startcloud_hostname
      - name: startcloud_dependencies
      - name: startcloud_service_user
      - name: startcloud_vagrant_readme
